#!/bin/bash

# init
do_compile=0

# get the files
files="$(sed '1d;$d' public/mix-manifest.json | sed -e 's|":.*||g' | sed -e 's|^[[:space:]]*"/|public/|g')"

# rm first and last line | remover everything behinnd the : | remove the part in the front | foreach
while read -r line ; do
    if git status --short | grep '^\w.' | grep $line ; then
        echo "need compile for $line"
        do_compile=1
    fi
done <<<"$(echo -e "$files")"

# run production and and add mix-manifest.json
if [ "$do_compile" = 1 ] ; then
    echo "running npm run production"
    PATH=$PATH:/usr/local/bin:/usr/local/sbin:/usr/local/Cellar/node@14/14.18.2/bin
    npm run production

    git add public/mix-manifest.json
fi

# add the compiled files to the commit
sed '1d;$d' public/mix-manifest.json | sed -e 's|":.*||g' | sed -e 's|^[[:space:]]*"/|public/|g' | while read -r line ; do
    if git status --short | grep '^\w.' | grep $line ; then
        echo "add $line to git"
        git add $line
    fi
done
